# -*- coding: utf-8 -*-
from __future__ import absolute_import

DBUS_ARMVE_PATH = '/ar/com/msa/VotAr/ARMVE'
DBUS_BUSNAME_ARMVE = 'ar.com.msa.VotAr.ARMVE'

# settings para DBUS
DBUS_BUSNAME_RFID = DBUS_BUSNAME_ARMVE
DBUS_BUSNAME_PRINTER = DBUS_BUSNAME_ARMVE
DBUS_BUSNAME_BACKLIGHT = DBUS_BUSNAME_ARMVE
DBUS_BUSNAME_POWERMANAGER = DBUS_BUSNAME_ARMVE
DBUS_BUSNAME_AGENT = DBUS_BUSNAME_ARMVE
DBUS_BUSNAME_FANCOOLERS = DBUS_BUSNAME_ARMVE
DBUS_BUSNAME_PIR = DBUS_BUSNAME_ARMVE

# paths
DBUS_LECTOR_PATH = DBUS_ARMVE_PATH
DBUS_IMPRESORA_PATH = DBUS_ARMVE_PATH
DBUS_BACKLIGHT_PATH = DBUS_ARMVE_PATH
DBUS_POWERMANAGER_PATH = DBUS_ARMVE_PATH
DBUS_AGENT_PATH = DBUS_ARMVE_PATH
DBUS_FANCOOLERS_PATH = DBUS_ARMVE_PATH
DBUS_PIR_PATH = DBUS_ARMVE_PATH

try:
    from msa.core.ipc.settings_local import *
except ImportError:
    pass
