PROTOCOL_VERSION_1 = 1
MINI_HEADER_BYTES = 4

MSG_COMMAND = 1
MSG_RESPONSE = 2
MSG_EV_PERS = 3
MSG_EV_NOPERS = 4
MSG_EV_DES = 5
MSG_EV_PUB = 6
MSG_ERROR = 255

DEV_AGENT = 0
DEV_PWR = 1
DEV_PRINTER = 2
DEV_RFID = 3  # definido para ISO15693
DEV_BACKLIGHT = 4
DEV_FAN_COOLERS = 5
DEV_PIR = 6
DEV_BUZZER = 7

# Para DEV_AGENT (0)
CMD_AGENT_INIT = 0
CMD_AGENT_LS_DEV = 1
CMD_AGENT_LS_EVENTS = 2
CMD_AGENT_RESET = 3
CMD_AGENT_RM_EVENTS = 4

EVT_AGENT_RESET = 128

INIT_RESPONSE_OK = 0
INIT_RESPONSE_ERR = 1

# Para DEV_PWR (1)
CMD_PWR_SOURCE = 0
CMD_PWR_CONNECTED = 1
CMD_PWR_GET_STATUS = 2
CMD_PWR_PARAMS = 3
CMD_PWR_CHECK = 4
CMD_PWR_SOURCE_CONTROL_MODE = 5
CMD_PWR_SOURCE_CONTROL = 6
CMD_PWR_ENABLE_SUSPEND = 7
CMD_PWR_GET_BATT_LEVEL = 8
CMD_PWR_SET_BATT_LEVEL = 9
CMD_PWR_GET_BATT_LOW_ALARM = 10
CMD_PWR_SET_BATT_LOW_ALARM = 11
CMD_PWR_SET_LEDS = 12

EVT_PWR_DISCHARGE = 128
EVT_PWR_LVL_MIN = 129
EVT_PWR_LVL_CRI = 130
EVT_PWR_LVL_MAX = 131
EVT_PWR_SWITCH_AC = 132
EVT_PWR_UNPLUGGED = 133
EVT_PWR_EMPTY = 134
EVT_PWR_PLUGGED = 135


# Para DEV_PRINTER (2)
CMD_PRINTER_GET_STATUS = 0
CMD_PRINTER_MOVE = 1
CMD_PRINTER_LOAD_BUFFER = 2
CMD_PRINTER_PRINT = 3
CMD_PRINTER_CLEAR_BUFFER = 4
CMD_PRINTER_PAPER_REMOVE = 5
CMD_PRINTER_PAPER_START = 6
CMD_PRINTER_GET_AUTOFEED = 7
CMD_PRINTER_SET_AUTOFEED = 8
CMD_PRINTER_LOAD_COMP_BUFFER = 9
CMD_PRINTER_GET_QUALITY = 10
CMD_PRINTER_SET_QUALITY = 11
CMD_PRINTER_MOVE_TO_SLOT = 12

EVT_PRINTER_PAPER_INSERTED = 128
EVT_PRINTER_PAPER_OUT_1 = 129
EVT_PRINTER_PAPER_OUT_2 = 130
EVT_PRINTER_PAPER_OUT_3 = 131

CMD_PRINTER_LOAD_COMP_BUFFER_HEADERS = 5

# Para DEV_RFID (3)
CMD_RFID_GET_TAGS = 0
CMD_RFID_SELECT_TAG = 1
CMD_RFID_READ_BLOCK = 2
CMD_RFID_READ_BLOCKS = 3
CMD_RFID_WRITE_BLOCK = 4
CMD_RFID_WRITE_BLOCKS = 5
CMD_RFID_IS_READONLY = 6
CMD_RFID_SET_RO_BLOCK = 7
CMD_RFID_SET_RO_BLOCKS = 8
CMD_RFID_CLEAR_BUFFER = 9
CMD_RFID_GET_ANTENNA_LVL = 10
CMD_RFID_SET_ANTENNA_LVL = 11
CMD_RFID_GET_ANTENNA_RCP_LVL = 12
CMD_RFID_GET_PWR_STATUS = 13
CMD_RFID_SET_PWR_STATUS = 14
CMD_RFID_SEND_RAW = 15

EVT_RFID_NEW_TAG = 128

# para DEV_BACKLIGHT (4)
CMD_BACKLIGHT_GET_BRIGHTNESS = 0
CMD_BACKLIGHT_SET_BRIGHTNESS = 1
CMD_BACKLIGHT_GET_STATUS = 2
CMD_BACKLIGHT_SET_STATUS = 3

# para DEV_FAN_COOLERS (5)
CMD_FAN_COOLERS_GET_SPEED = 0
CMD_FAN_COOLERS_SET_SPEED = 1

# para DEV_PIR (6)
CMD_PIR_STATUS = 0

EVT_PIR_DETECTED = 128
EVT_PIR_NOT_DETECTED = 129

# para DEV_BUZZER (7)
CMD_BUZZER_BUZZ = 1

# codigos de error enviados por el ARM
AVE_VERSION_ERROR = 1
AVE_SIZE_ERROR = 2
AVE_MESSAGE_NOT_FOUND = 3
AVE_DEVICE_NOT_SUPPORTED = 4
AVE_COMMAND_NOT_SUPPORTED = 5
AVE_INSUFFICIENT_PARAMETERS = 6
AVE_TO_MANY_PARAMETERS = 7
AVE_WRONG_PARAMETERS = 8
AVE_RFID_NOT_RESPONSE = 9
AVE_ISO15693_ERROR = 10
AVE_RFID_BLOCKS_ALREADY_LOCKED = 11
AVE_RFID_TAG_NOT_SELECTED = 12
AVE_BUSY = 13
AVE_RFID_DISABLED = 14
# No hay codigo de error 15.
AVE_RFID_TX_TIMEOUT = 16
AVE_RFID_RX_TIMEOUT = 17
AVE_RFID_ERROR_FIFO = 18
AVE_RFID_ERROR_DRV = 19
AVE_RFID_UNKNOWN_ERROR = 20
AVE_AGENT_RESET_ERROR = 21

AUTOFEED_OFF = 0
AUTOFEED_1 = 255
AUTOFEED_2 = 15
AUTOFEED_SELECT = -1

AUTOFEED_DEFAULT = AUTOFEED_SELECT

PRINT_SLOW = 0
PRINT_LOW = 17
PRINT_MID = 34
PRINT_HIGH = 51
PRINT_SHIGH = 68

PRINT_DEFAULT = PRINT_LOW
PRINT_STEP = 17 #  Calculada de la separacion entre los distintos niveles
