# -*- coding: utf-8 -*-
TAG_VOTO = 'TAG_VOTO'
TAG_USUARIO_MSA = 'TAG_USUARIO_MSA'
TAG_PRESIDENTE_MESA = 'TAG_PRESIDENTE_MESA'
TAG_RECUENTO = 'TAG_RECUENTO'
TAG_APERTURA = 'TAG_APERTURA'
TAG_DEMO = 'TAG_DEMO'
TAG_VIRGEN = 'TAG_VIRGEN'
TAG_DESCONOCIDO = 'TAG_DESCONOCIDO'

TAGS_ADMIN = (TAG_USUARIO_MSA, TAG_PRESIDENTE_MESA, TAG_DEMO)

CLASE_ICODE = 'ICODE'
CLASE_ICODE2 = 'ICODE2'
CLASE_MIFARE = 'MIFARE'

NO_TAG = 'sin tag'
TAG_VACIO = 'tag vacio'
TAG_DATOS = 'tag con datos'
TAG_ADMIN = 'tag admin'
TAG_ERROR = 'error en tag'
TAG_COLISION = 'colision al leer tag'
TAG_INICIO = 'tag recuento parte 1'
TAG_ADDENDUM = 'tag recuento parte 2'
CNX_ERROR = u'error de conexión'
TAG_NO_ENTRA = u'HLQP'

COD_TAG_VACIO = 0
COD_TAG_VOTO = 1
COD_TAG_USUARIO_MSA = 2
COD_TAG_PRESIDENTE_MESA = 3
COD_TAG_RECUENTO = 4
COD_TAG_APERTURA = 5
COD_TAG_DEMO = 6
COD_TAG_VIRGEN = 7
COD_TAG_DESCONOCIDO = 255
COD_TAG_INICIO = 127
COD_TAG_ADDENDUM = 128
COD_TAG_NO_ENTRA = 69

TIPOS_TAGS = {
    COD_TAG_VACIO: TAG_VACIO,
    COD_TAG_VOTO: TAG_VOTO,
    COD_TAG_USUARIO_MSA: TAG_USUARIO_MSA,
    COD_TAG_PRESIDENTE_MESA: TAG_PRESIDENTE_MESA,
    COD_TAG_RECUENTO: TAG_RECUENTO,
    COD_TAG_APERTURA: TAG_APERTURA,
    COD_TAG_DEMO: TAG_DEMO,
    COD_TAG_VIRGEN: TAG_VIRGEN,
    COD_TAG_DESCONOCIDO: TAG_DESCONOCIDO,
    COD_TAG_INICIO: TAG_INICIO,
    COD_TAG_ADDENDUM: TAG_ADDENDUM,
    COD_TAG_NO_ENTRA: TAG_NO_ENTRA
}

TIPOS_TAGS_REV = dict(zip(TIPOS_TAGS.values(), TIPOS_TAGS.keys()))
